# Generated by Django 3.2.16 on 2024-02-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',), 'verbose_name': 'коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_published',
        ),
    ]
