# Generated by Django 3.2.16 on 2024-02-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='Post_images', verbose_name='Фото'),
        ),
    ]
